/**
 * Created by Shayakhmetov on 24.11.2016.
 */

/**
 * VoiceArt module.
 * @module VoiceArt
 * @type {Object}
 * @property {ItemRenderer} ItemRenderer - Tool for rendering task forms from json
 * @property {VoiceController} VoiceController - Extensible tool that allows you to work with tasks (including generated by ItemRenderer) using voice commands
 */
var VoiceController = require('./voice-controller');
var ItemRenderer = require('./item-renderer');
var VoiceCommander = require('./voice-controller/commander');

module.exports = {
    ItemRenderer: ItemRenderer,
    VoiceController: VoiceController,
    VoiceCommander: VoiceCommander
};